insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('14', '57', '47', 'Offensive content', true, '35');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('12', '33', '56', 'Irrelevant topic', false, '40');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('22', '18', '13', 'Inappropriate language', true, '36');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('17', '56', '5', 'Spam', false, '39');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('18', '47', '58', 'Irrelevant topic', false, '10');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('24', '30', '21', 'Offensive content', false, '25');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('44', '20', '8', 'Personal attacks', false, '27');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('31', '22', '39', 'Inappropriate language', false, '12');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('10', '38', '30', 'Spam', false, '18');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('35', '40', '10', 'Irrelevant topic', true, '31');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('4', '45', '36', 'Irrelevant topic', false, '21');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('38', '7', '24', 'Inappropriate language', false, '3');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('8', '9', '45', 'Spam', false, '26');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('29', '48', '37', 'Personal attacks', false, '43');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('6', '11', '43', 'Personal attacks', false, '37');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('27', '53', '4', 'Offensive content', true, '28');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('52', '17', '29', 'Spam', false, '7');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('54', '28', '7', 'Personal attacks', true, '8');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('47', '6', '42', 'Irrelevant topic', true, '15');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('60', '25', '27', 'Personal attacks', false, '6');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('41', '3', '53', 'Offensive content', false, '23');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('13', '43', '32', 'Spam', false, '34');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('20', '51', '51', 'Irrelevant topic', true, '5');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('40', '27', '60', 'Irrelevant topic', true, '45');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('43', '34', '59', 'Offensive content', false, '22');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('39', '31', '12', 'Offensive content', true, '30');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('37', '26', '46', 'Offensive content', false, '14');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('48', '46', '28', 'Offensive content', false, '1');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('53', '42', '14', 'Spam', false, '29');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('45', '2', '3', 'Personal attacks', true, '24');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('2', '21', '22', 'Offensive content', false, '9');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('5', '36', '34', 'Spam', true, '16');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('15', '1', '6', 'Personal attacks', true, '11');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('50', '29', '31', 'Inappropriate language', false, '38');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('57', '60', '20', 'Offensive content', true, '44');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('32', '44', '2', 'Irrelevant topic', false, '2');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('23', '41', '55', 'Spam', false, '20');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('51', '16', '26', 'Offensive content', true, '13');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('55', '52', '33', 'Irrelevant topic', true, '4');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('25', '49', '9', 'Offensive content', false, '33');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('30', '50', '50', 'Offensive content', true, '19');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('46', '24', '11', 'Offensive content', false, '41');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('3', '59', '54', 'Spam', false, '32');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('58', '15', '41', 'Irrelevant topic', false, '17');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('49', '14', '1', 'Offensive content', false, '42');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('19', '39', '52', 'Inappropriate language', false, '9');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('36', '12', '48', 'Inappropriate language', false, '43');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('34', '5', '19', 'Spam', false, '10');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('26', '19', '23', 'Personal attacks', false, '37');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('9', '55', '44', 'Spam', false, '21');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('11', '37', '57', 'Spam', false, '28');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('28', '23', '25', 'Offensive content', false, '5');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('42', '32', '35', 'Irrelevant topic', false, '23');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('7', '35', '40', 'Irrelevant topic', false, '14');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('33', '10', '17', 'Personal attacks', true, '15');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('59', '4', '38', 'Spam', false, '17');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('56', '13', '16', 'Spam', true, '20');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('1', '54', '15', 'Irrelevant topic', true, '40');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('21', '58', '18', 'Offensive content', true, '4');
insert into report_data (authorID, reporteeID, reportedMessage, reasoning, resolved, moderatorID) values ('16', '8', '49', 'Inappropriate language', false, '35');
