USE virtualStudyGroupOrganizer_db;

insert into review (reviewID, review, rating, groupID, author) values (1, 'The study group session was extremely helpful and productive.', 4, '6', '20');
insert into review (reviewID, review, rating, groupID, author) values (2, 'I found the study group session to be somewhat beneficial.', 4, '29', '60');
insert into review (reviewID, review, rating, groupID, author) values (3, 'I didn''t find the study group session useful at all.', 3, '21', '36');
insert into review (reviewID, review, rating, groupID, author) values (4, 'I didn''t find the study group session useful at all.', 4, '22', '28');
insert into review (reviewID, review, rating, groupID, author) values (5, 'I found the study group session to be somewhat beneficial.', 4, '25', '47');
insert into review (reviewID, review, rating, groupID, author) values (6, 'The study group session was not very helpful in my opinion.', 5, '54', '24');
insert into review (reviewID, review, rating, groupID, author) values (7, 'I didn''t find the study group session useful at all.', 4, '16', '58');
insert into review (reviewID, review, rating, groupID, author) values (8, 'The study group session was not very helpful in my opinion.', 5, '49', '39');
insert into review (reviewID, review, rating, groupID, author) values (9, 'I didn''t find the study group session useful at all.', 5, '51', '29');
insert into review (reviewID, review, rating, groupID, author) values (10, 'The study group session was extremely helpful and productive.', 4, '45', '27');
insert into review (reviewID, review, rating, groupID, author) values (11, 'The study group session was extremely helpful and productive.', 2, '43', '9');
insert into review (reviewID, review, rating, groupID, author) values (12, 'The study group session was extremely helpful and productive.', 4, '7', '54');
insert into review (reviewID, review, rating, groupID, author) values (13, 'The study group session was not very helpful in my opinion.', 1, '9', '35');
insert into review (reviewID, review, rating, groupID, author) values (14, 'The study group session was not very helpful in my opinion.', 4, '36', '18');
insert into review (reviewID, review, rating, groupID, author) values (15, 'The study group session was not very helpful in my opinion.', 2, '33', '3');
insert into review (reviewID, review, rating, groupID, author) values (16, 'The study group session was not very helpful in my opinion.', 2, '35', '45');
insert into review (reviewID, review, rating, groupID, author) values (17, 'The study group session was extremely helpful and productive.', 3, '30', '10');
insert into review (reviewID, review, rating, groupID, author) values (18, 'The study group session was extremely helpful and productive.', 1, '50', '6');
insert into review (reviewID, review, rating, groupID, author) values (19, 'I didn''t find the study group session useful at all.', 1, '17', '11');
insert into review (reviewID, review, rating, groupID, author) values (20, 'The study group session was extremely helpful and productive.', 3, '19', '55');
insert into review (reviewID, review, rating, groupID, author) values (21, 'The study group session was extremely helpful and productive.', 1, '59', '26');
insert into review (reviewID, review, rating, groupID, author) values (22, 'The study group session was extremely helpful and productive.', 3, '32', '22');
insert into review (reviewID, review, rating, groupID, author) values (23, 'The study group session was extremely helpful and productive.', 5, '5', '57');
insert into review (reviewID, review, rating, groupID, author) values (24, 'I didn''t find the study group session useful at all.', 4, '15', '37');
insert into review (reviewID, review, rating, groupID, author) values (25, 'The study group session was not very helpful in my opinion.', 5, '2', '48');
insert into review (reviewID, review, rating, groupID, author) values (26, 'The study group session was not very helpful in my opinion.', 1, '4', '51');
insert into review (reviewID, review, rating, groupID, author) values (27, 'I found the study group session to be somewhat beneficial.', 2, '55', '8');
insert into review (reviewID, review, rating, groupID, author) values (28, 'I didn''t find the study group session useful at all.', 3, '46', '30');
insert into review (reviewID, review, rating, groupID, author) values (29, 'I found the study group session to be somewhat beneficial.', 5, '11', '49');
insert into review (reviewID, review, rating, groupID, author) values (30, 'The study group session was extremely helpful and productive.', 2, '18', '59');
insert into review (reviewID, review, rating, groupID, author) values (31, 'The study group session was not very helpful in my opinion.', 4, '12', '5');
insert into review (reviewID, review, rating, groupID, author) values (32, 'The study group session was not very helpful in my opinion.', 3, '13', '52');
insert into review (reviewID, review, rating, groupID, author) values (33, 'I didn''t find the study group session useful at all.', 1, '27', '23');
insert into review (reviewID, review, rating, groupID, author) values (34, 'The study group session was extremely helpful and productive.', 5, '31', '34');
insert into review (reviewID, review, rating, groupID, author) values (35, 'The study group session was extremely helpful and productive.', 1, '52', '14');
insert into review (reviewID, review, rating, groupID, author) values (36, 'I didn''t find the study group session useful at all.', 4, '10', '53');
insert into review (reviewID, review, rating, groupID, author) values (37, 'The study group session was not very helpful in my opinion.', 1, '48', '15');
insert into review (reviewID, review, rating, groupID, author) values (38, 'I found the study group session to be somewhat beneficial.', 5, '3', '1');
insert into review (reviewID, review, rating, groupID, author) values (39, 'I didn''t find the study group session useful at all.', 3, '26', '7');
insert into review (reviewID, review, rating, groupID, author) values (40, 'The study group session was not very helpful in my opinion.', 3, '34', '32');
insert into review (reviewID, review, rating, groupID, author) values (41, 'I found the study group session to be somewhat beneficial.', 1, '56', '33');
insert into review (reviewID, review, rating, groupID, author) values (42, 'The study group session was extremely helpful and productive.', 5, '14', '46');
insert into review (reviewID, review, rating, groupID, author) values (43, 'The study group session was not very helpful in my opinion.', 2, '8', '16');
insert into review (reviewID, review, rating, groupID, author) values (44, 'I didn''t find the study group session useful at all.', 2, '60', '41');
insert into review (reviewID, review, rating, groupID, author) values (45, 'I didn''t find the study group session useful at all.', 5, '38', '56');
insert into review (reviewID, review, rating, groupID, author) values (46, 'The study group session was not very helpful in my opinion.', 1, '24', '38');
insert into review (reviewID, review, rating, groupID, author) values (47, 'I didn''t find the study group session useful at all.', 1, '37', '4');
insert into review (reviewID, review, rating, groupID, author) values (48, 'I found the study group session to be somewhat beneficial.', 2, '53', '43');
insert into review (reviewID, review, rating, groupID, author) values (49, 'The study group session was not very helpful in my opinion.', 5, '57', '31');
insert into review (reviewID, review, rating, groupID, author) values (50, 'The study group session was not very helpful in my opinion.', 1, '1', '2');
insert into review (reviewID, review, rating, groupID, author) values (51, 'The study group session was extremely helpful and productive.', 3, '42', '44');
insert into review (reviewID, review, rating, groupID, author) values (52, 'I didn''t find the study group session useful at all.', 3, '41', '50');
insert into review (reviewID, review, rating, groupID, author) values (53, 'The study group session was extremely helpful and productive.', 3, '44', '40');
insert into review (reviewID, review, rating, groupID, author) values (54, 'I didn''t find the study group session useful at all.', 5, '40', '19');
insert into review (reviewID, review, rating, groupID, author) values (55, 'I found the study group session to be somewhat beneficial.', 5, '47', '13');
insert into review (reviewID, review, rating, groupID, author) values (56, 'I found the study group session to be somewhat beneficial.', 1, '28', '17');
insert into review (reviewID, review, rating, groupID, author) values (57, 'The study group session was not very helpful in my opinion.', 1, '23', '25');
insert into review (reviewID, review, rating, groupID, author) values (58, 'The study group session was not very helpful in my opinion.', 5, '20', '21');
insert into review (reviewID, review, rating, groupID, author) values (59, 'I didn''t find the study group session useful at all.', 3, '58', '12');
insert into review (reviewID, review, rating, groupID, author) values (60, 'The study group session was extremely helpful and productive.', 3, '39', '42');
