insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (1, 'Michelina', 'Lorenc', 'Sociology', 2025, false, '8', '14');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (2, 'Jessalin', 'Casajuana', 'English Literature', 2025, true, '7', '28');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (3, 'Tremayne', 'McMylor', 'English Literature', 2027, false, '27', '38');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (4, 'Thaddeus', 'Farfolomeev', 'Sociology', 2026, false, '9', '18');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (5, 'Di', 'McIlmurray', 'History', 2026, false, '25', '1');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (6, 'Carley', 'Norwich', 'Sociology', 2027, false, '43', '39');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (7, 'Libbie', 'Robben', 'English Literature', 2023, false, '39', '24');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (8, 'Pearla', 'Gian', 'Psychology', 2024, false, '44', '6');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (9, 'Skyler', 'Soff', 'Computer Science', 2028, false, '26', '8');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (10, 'Lynda', 'Herkess', 'Biology', 2027, false, '47', '42');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (11, 'Feodor', 'Kelso', 'Sociology', 2025, false, '46', '29');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (12, 'Engracia', 'Hundell', 'Sociology', 2026, false, '16', '34');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (13, 'Bert', 'Tansly', 'Art', 2025, false, '21', '23');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (14, 'Derrick', 'Bydaway', 'History', 2024, false, '38', '20');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (15, 'Maxy', 'Liverseege', 'Biology', 2023, false, '50', '32');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (16, 'Curcio', 'Gelletly', 'Sociology', 2026, false, '59', '3');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (17, 'Bellina', 'Haney`', 'Psychology', 2023, false, '30', '5');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (18, 'Mandy', 'Brahms', 'Computer Science', 2026, false, '57', '26');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (19, 'Hyman', 'Bulmer', 'Business Administration', 2026, false, '5', '45');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (20, 'Amargo', 'Blatchford', 'Art', 2027, false, '28', '2');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (21, 'Granthem', 'Gilbart', 'History', 2023, false, '15', '15');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (22, 'Alicea', 'Rigardeau', 'Art', 2027, false, '3', '25');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (23, 'Yelena', 'Anglish', 'Engineering', 2027, false, '60', '40');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (24, 'Franky', 'Mirams', 'Sociology', 2024, false, '11', '21');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (25, 'Benedick', 'Haisell', 'Business Administration', 2027, false, '48', '10');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (26, 'Scarlet', 'Haldane', 'Computer Science', 2027, false, '36', '22');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (27, 'Hersch', 'Longwood', 'Business Administration', 2027, false, '13', '33');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (28, 'Engelbert', 'Parman', 'Sociology', 2025, false, '22', '36');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (29, 'Verla', 'O''Crotty', 'Psychology', 2025, false, '32', '16');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (30, 'Kelbee', 'Caghy', 'Sociology', 2023, false, '52', '13');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (31, 'Dorothy', 'Hance', 'Sociology', 2027, false, '56', '31');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (32, 'Constantin', 'Cansdill', 'Psychology', 2027, false, '49', '11');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (33, 'Randene', 'Gutowski', 'Psychology', 2027, false, '58', '12');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (34, 'Joel', 'Cromack', 'Computer Science', 2025, false, '54', '27');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (35, 'Celene', 'Trolley', 'Biology', 2023, false, '6', '19');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (36, 'Marguerite', 'Winkell', 'Computer Science', 2026, false, '19', '4');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (37, 'Cindi', 'Cadding', 'Biology', 2025, false, '14', '30');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (38, 'Zorah', 'Le Galle', 'Engineering', 2025, false, '45', '44');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (39, 'Lana', 'Walthew', 'Art', 2024, false, '18', '7');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (40, 'Raynor', 'Giovannini', 'History', 2023, false, '33', '37');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (41, 'Chadwick', 'Swalteridge', 'Biology', 2024, false, '23', '35');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (42, 'Chanda', 'Thomtson', 'Psychology', 2028, false, '4', '43');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (43, 'Fletcher', 'Walpole', 'Engineering', 2023, false, '40', '17');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (44, 'Teriann', 'Bugs', 'Engineering', 2028, false, '31', '41');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (45, 'Bar', 'Zuanazzi', 'English Literature', 2025, false, '1', '9');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (46, 'Devin', 'Ashbolt', 'Mathematics', 2024, false, '55', '38');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (47, 'Bram', 'Volks', 'Psychology', 2028, false, '12', '14');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (48, 'Della', 'Fowell', 'Engineering', 2028, false, '20', '36');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (49, 'Garnette', 'Reichelt', 'Psychology', 2025, false, '37', '34');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (50, 'Jacky', 'Bonnor', 'Computer Science', 2024, false, '41', '35');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (51, 'Halsy', 'Wanley', 'Biology', 2028, false, '53', '41');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (52, 'Ashley', 'MacEnelly', 'Computer Science', 2024, false, '2', '16');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (53, 'Irita', 'Zanolli', 'Computer Science', 2024, false, '17', '19');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (54, 'Joline', 'Haggidon', 'Art', 2027, false, '10', '32');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (55, 'Godfree', 'Petran', 'Biology', 2025, false, '29', '40');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (56, 'Olympe', 'Viscovi', 'Computer Science', 2025, false, '51', '9');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (57, 'Katleen', 'O''Hear', 'History', 2028, false, '34', '39');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (58, 'Dyna', 'McGonigle', 'Psychology', 2028, false, '42', '15');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (59, 'Trudie', 'Sancias', 'Mathematics', 2027, false, '24', '45');
insert into user (userID, first_name, last_name, major, year, banned, preferredSubject, moderatorID) values (60, 'Debby', 'Linney', 'English Literature', 2023, false, '35', '26');
